export const NATIONALITY: Record<string, any> = {
  Argentina: require("@/assets/flags/argentina.png"),
  Armenia: require("@/assets/flags/armenia.png"),
  Austria: require("@/assets/flags/austria.png"),
  Bahrain: require("@/assets/flags/bahrain.png"),
  Belgium: require("@/assets/flags/belgium.png"),
  Brazil: require("@/assets/flags/brazil.png"),
  Bulgaria: require("@/assets/flags/bulgaria.png"),
  Cambodia: require("@/assets/flags/cambodia.png"),
  Cameroon: require("@/assets/flags/cameroon.png"),
  Canada: require("@/assets/flags/canada.png"),
  Chile: require("@/assets/flags/chile.png"),
  China: require("@/assets/flags/china.png"),
  Colombia: require("@/assets/flags/colombia.png"),
  "Costa-rica": require("@/assets/flags/costa-rica.png"),
  Croatia: require("@/assets/flags/croatia.png"),
  Cuba: require("@/assets/flags/cuba.png"),
  "Czech Republic": require("@/assets/flags/czech-republic.png"),
  "Democratic Republic Of Congo": require("@/assets/flags/democratic-republic-of-congo.png"),
  Denmark: require("@/assets/flags/denmark.png"),
  Ecuador: require("@/assets/flags/ecuador.png"),
  "El Salvador": require("@/assets/flags/el-salvador.png"),
  England: require("@/assets/flags/england.png"),
  Estonia: require("@/assets/flags/estonia.png"),
  Finland: require("@/assets/flags/finland.png"),
  France: require("@/assets/flags/france.png"),
  Georgia: require("@/assets/flags/georgia.png"),
  Germany: require("@/assets/flags/germany.png"),
  Ghana: require("@/assets/flags/ghana.png"),
  Greece: require("@/assets/flags/greece.png"),
  Honduras: require("@/assets/flags/honduras.png"),
  "Hong Kong": require("@/assets/flags/hong-kong.png"),
  Hungary: require("@/assets/flags/hungary.png"),
  Iceland: require("@/assets/flags/iceland.png"),
  Ireland: require("@/assets/flags/ireland.png"),
  Israel: require("@/assets/flags/israel.png"),
  Italy: require("@/assets/flags/italy.png"),
  "Ivory Coast": require("@/assets/flags/ivory-coast.png"),
  Japan: require("@/assets/flags/japan.png"),
  Jordan: require("@/assets/flags/jordan.png"),
  Kenya: require("@/assets/flags/kenya.png"),
  Kuwait: require("@/assets/flags/kuwait.png"),
  Laos: require("@/assets/flags/laos.png"),
  Latvia: require("@/assets/flags/latvia.png"),
  Lithuania: require("@/assets/flags/lithuania.png"),
  Luxembourg: require("@/assets/flags/luxembourg.png"),
  Malaysia: require("@/assets/flags/malaysia.png"),
  Mali: require("@/assets/flags/mali.png"),
  Malta: require("@/assets/flags/malta.png"),
  Morocco: require("@/assets/flags/morocco.png"),
  Myanmar: require("@/assets/flags/myanmar.png"),
  Nepal: require("@/assets/flags/nepal.png"),
  Netherlands: require("@/assets/flags/netherlands.png"),
  Nicaragua: require("@/assets/flags/nicaragua.png"),
  Norway: require("@/assets/flags/norway.png"),
  Oman: require("@/assets/flags/oman.png"),
  Panama: require("@/assets/flags/panama.png"),
  Panama: require("@/assets/flags/panama.png"),
  Peru: require("@/assets/flags/peru.png"),
  Philippines: require("@/assets/flags/philippines.png"),
  Poland: require("@/assets/flags/poland.png"),
  Qatar: require("@/assets/flags/qatar.png"),
  Romania: require("@/assets/flags/romania.png"),
  Russia: require("@/assets/flags/russia.png"),
  Ringapore: require("@/assets/flags/singapore.png"),
  Slovakia: require("@/assets/flags/slovakia.png"),
  "South-africa": require("@/assets/flags/south-africa.png"),
  "South-korea": require("@/assets/flags/south-korea.png"),
  Spain: require("@/assets/flags/spain.png"),
  Sweden: require("@/assets/flags/sweden.png"),
  Switzerland: require("@/assets/flags/switzerland.png"),
  Taiwan: require("@/assets/flags/taiwan.png"),
  Thailand: require("@/assets/flags/thailand.png"),
  Tunisia: require("@/assets/flags/tunisia.png"),
  Turkey: require("@/assets/flags/turkey.png"),
  "United-kingdom": require("@/assets/flags/united-kingdom.png"),
  "United-states": require("@/assets/flags/united-states.png"),
  Uzbekistan: require("@/assets/flags/uzbekistan.png"),
  Vietnam: require("@/assets/flags/vietnam.png"),
};

export function nationalityIcon(id?: string | null): string {
  if (!id) return "Flag non trovata";
  return NATIONALITY[id] ?? "Flag non trovata";
}
